---
name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  trigger:
    uses: statnett/workflows/.github/workflows/lint-pr.yml@main
    permissions:
      contents: read
      pull-requests: write
      statuses: write
