---
name: Release Please

on:
  push:
    branches:
      - main

jobs:
  trigger:
    uses: statnett/workflows/.github/workflows/release-please.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
