---
name: Test

on:
  push:
    paths-ignore:
      - README.md

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Test
        run: make test

  snapshot:
    name: Test Snapshot Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: GoReleaser Build Snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot
